import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
const B=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const SK=process.env.PRESENTATIONS_SKILL_DIR;
if(!SK || !process.env.RUNTIME_PYTHON) throw new Error('Definir PRESENTATIONS_SKILL_DIR, RUNTIME_PYTHON y RUNTIME_NODE_MODULES del runtime de artefactos');
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(SK,'container_tools/artifact_tool_utils.mjs')).href);
const r=JSON.parse(await fs.readFile(B+'/resultados/evaluacion.json','utf8'));
const geo=JSON.parse(await fs.readFile(B+'/resultados/eda_paises.json','utf8')).sort((a,b)=>b.n-a.n).slice(0,5);
const family=resolvePresentationFont({fontFamily:'Arial'});const p=Presentation.create({slideSize:{width:1280,height:720}});
const red='#8C1D22',dark='#2B2B2B',gray='#626262';let speeches=[];
function txt(s,t,x,y,w,h,size=28,color=dark,bold=false){let q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=t;q.text.style={typeface:family,fontSize:size,color,bold,autoFit:'none'};return q;}
function slide(title,body,source='Elaboración propia. resultados/evaluacion.json',darkBg=false){let s=p.slides.add();s.background.fill=darkBg?red:'#FFFFFF';txt(s,title,75,52,1130,115,44,darkBg?'#FFFFFF':red,true);txt(s,String(p.slides.items.length),1160,671,45,25,17,darkBg?'#FFFFFF':gray);s.speakerNotes.textFrame.setText(body+'\n\nFuentes: '+source);speeches.push({title,text:body});return s;}
function chart(s,categories,values,y=200,h=350,format='0.000',label='RMSE',color=red){let c=s.charts.add('bar',{position:{left:90,top:y,width:1060,height:h},categories,series:[{name:label,values:values.map(v=>Number(v.toFixed(6))),fill:color,valuesFormatCode:format}],barOptions:{direction:'bar',grouping:'clustered'},hasLegend:false,dataLabels:{showValue:true,position:'outEnd',numberFormatCode:format,textStyle:{fontFamily:family,fontSize:23}},xAxis:{textStyle:{fontFamily:family,fontSize:23}},yAxis:{textStyle:{fontFamily:family,fontSize:21},numberFormatCode:format},chartFill:'#FFFFFF'});applyPresentationChartFont(c,{fontFamily:family});return c;}
let s=slide('Gastronomía asiática\nen Europa','Hola, soy Peng Chen. Mi trabajo analiza restaurantes asiáticos en Europa, con especial foco en España. Combina análisis exploratorio, predicción de valoración y una aplicación local. Mi interés inicial por abrir un buffet de sushi en Madrid sirve como motivación, pero distingo esa decisión de lo que realmente permite demostrar el dataset.','Propuesta aprobada y memoria revisada, sección 1.',true);
txt(s,'Análisis y predicción de valoración\ncon especial foco en España',80,265,1100,110,34,'#F4E9D8');txt(s,'Peng Chen',80,490,1100,45,29,'#FFFFFF',true);txt(s,'TFM · Big Data, Data Science e Inteligencia Artificial\nUCM Online · Septiembre 2026',80,551,1100,80,23,'#FFFFFF');
s=slide('Datos y adecuación al problema','Parto de TripAdvisor European Restaurants, publicado en 2021. El filtro asiático contiene 86.306 restaurantes, y 81.315 tienen valoración válida. Verifiqué la licencia CC0 declarada en la API de Kaggle. La muestra es histórica y depende de la cobertura de la plataforma. Por eso no la trato como un censo actual ni como una base de beneficios empresariales.','Kaggle: https://www.kaggle.com/datasets/stefanoleone992/tripadvisor-european-restaurants; resultados/kaggle_metadata.json y evaluacion.json.');
txt(s,'86.306 restaurantes asiáticos',80,190,1100,60,40,dark,true);txt(s,'81.315 con rating válido · 42 columnas de origen',80,265,1100,55,29);txt(s,'Snapshot de 2021 · licencia declarada CC0',80,355,1100,55,29);txt(s,'Limitación: cobertura de plataforma, datos ausentes y ausencia de ventas o beneficios',80,475,1100,105,31,red);
s=slide('Comparación europea y foco en España','England, France, Germany y Spain concentran una parte importante de los registros. España aporta 8.295 restaurantes. Conservo las etiquetas originales: England no equivale a todo el Reino Unido. Además, la ciudad está incompleta en muchos registros españoles, por lo que no afirmo que Madrid sea el mayor mercado. Las diferencias geográficas describen la muestra, no oportunidades de inversión demostradas.','Elaboración propia: resultados/eda_paises.json y eda_extra.json.');
chart(s,geo.map(d=>d.country),geo.map(d=>d.n),175,380,'#,##0','Registros');txt(s,'24 etiquetas territoriales; no 24 estados soberanos\nLos recuentos no son un censo completo del mercado',80,575,1100,70,25,gray);
s=slide('Predicción y disponibilidad de información','Comparo dos variantes. La primera utiliza ubicación, horarios, precio, dietas y cocinas. La segunda añade comida, servicio, valor, ambiente y número de reseñas. Estas opiniones ya existentes están estrechamente relacionadas con el rating objetivo. La comparación permite comprobar cuánto depende el resultado de información reputacional. Ninguna variante se ha validado como predicción de una nueva apertura.');
txt(s,'Sin reputación',80,185,1100,55,34,red,true);txt(s,'Ubicación, horarios, precio, dietas y etiquetas de cocina',80,246,1100,75,30);txt(s,'Con reputación',80,350,1100,55,34,red,true);txt(s,'Las anteriores + subpuntuaciones y número de reseñas',80,413,1100,80,30);txt(s,'Objetivo: rating histórico de establecimientos existentes',80,550,1100,65,28,dark,true);
s=slide('Selección de modelos en validación','Separé entrenamiento, validación y test, estratificando por territorio. La imputación y codificación se ajustan dentro del pipeline. Comparé una referencia de media, regresión lineal, Random Forest y XGBoost. Seleccioné el algoritmo por validación y reservé el test para evaluación final. La diferencia entre los dos conjuntos de árboles sin reputación es pequeña; no la presento como una superioridad general de Random Forest.');
const vals=r.validation.filter(x=>x.conjunto==='sin_reputacion');const rows=[['Modelo sin reputación','RMSE validación','MAE validación'],...vals.map(a=>[a.modelo,a.RMSE.toFixed(3),a.MAE.toFixed(3)])];
let table=s.tables.add({rows:5,columns:3,left:80,top:225,width:1120,height:290,columnWidths:[530,295,295],values:rows});
for(let i=0;i<5;i++)for(let j=0;j<3;j++){let c=table.getCell(i,j);c.fill=i===0?'#F4E9D8':i%2?'#F7F7F7':'#FFFFFF';c.text.style={typeface:family,fontSize:25,color:dark,bold:i===0};}
txt(s,'60% entrenamiento · 20% validación · 20% test',80,170,1100,45,28);txt(s,'Selección por RMSE; reajuste final con el 80% de los datos',80,558,1100,70,27,gray);
s=slide('Error de predicción en test: RMSE','En las mismas 16.263 observaciones de test, la referencia tiene un RMSE de 0,695. Sin reputación, Random Forest baja a 0,625 y su error absoluto medio es de 0,462 puntos. Con reputación, XGBoost alcanza 0,542 de RMSE y 0,361 de error absoluto medio. La mejora es real en esta muestra, pero no demuestra capacidad para predecir rentabilidad ni generalización a datos actuales.');
chart(s,['Media de entrenamiento','Sin reputación · RF','Con reputación · XGB'],[r.test.sin_reputacion.baseline_media.RMSE,r.test.sin_reputacion.RMSE,r.test.con_reputacion.RMSE],180,350);
txt(s,'MAE: 0,462 sin reputación · 0,361 con reputación',80,550,1100,55,30,red,true);txt(s,'Test común: 16.263 restaurantes · menor error es mejor',80,610,1100,35,23,gray);
s=slide('Interpretabilidad y límites','Recalculé la importancia mediante permutación sobre una muestra de validación. Sin reputación destacan algunas etiquetas y horarios; con reputación destacan comida y servicio. El gráfico muestra cuánto empeora el error al desordenar una variable. Esto explica dependencia del modelo, no el efecto causal de cambiar el negocio. Las variables correlacionadas y la falta de información pueden influir en ese orden.');
let imp=r.permutation_validation.sin_reputacion.slice(0,5);let labels={'cuisine_chinese':'Etiqueta Chinese','vegan_options':'Opciones veganas','open_days_per_week':'Días abiertos','longitude':'Longitud','vegetarian_friendly':'Opciones vegetarianas'};chart(s,imp.map(x=>labels[x.feature]||x.feature),imp.map(x=>x.delta_RMSE),180,360,'0.000','Aumento de RMSE');txt(s,'Aumento de RMSE al permutar · 1.200 filas · 3 repeticiones',80,560,1100,45,24,gray);txt(s,'Importancia predictiva no equivale a efecto causal',80,615,1100,45,28,red,true);
s=slide('Productivización del modelo','El modelo sin reputación se integra en una aplicación local. El usuario introduce características y recibe una estimación identificada por versión. El sistema comprueba tipos, rangos y correspondencia entre país y región; informa de los valores imputados. Probé que la API coincide con el pipeline y rechaza entradas inválidas. Hay contadores básicos de uso y ausencias, aunque todavía no es un servicio empresarial desplegado.','src/servir.py, src/interfaz.html, src/verificar.py y resultados/evaluacion.json.');
txt(s,'Entrada validada → pipeline → rating estimado',80,195,1120,65,35,dark,true);txt(s,'Interfaz web y API local\nVersión y hash del modelo\nControl de errores, latencia y campos ausentes',80,300,1110,185,31);txt(s,'Prototipo funcional: sin publicación externa ni validación de impacto empresarial',80,540,1100,90,29,red);
s=slide('Madrid como aplicación complementaria','Para Madrid incorporé censo de locales, padrón, renta del INE y ofertas de restaurantes. Estas fuentes mejoran el contexto y la discusión de actualidad, pero no aportan directamente ventas futuras. No interpreto unos pocos buffets etiquetados como el total de competidores. Los escenarios de equilibrio permanecen como anexo: calculan condiciones bajo supuestos, sin demostrar que una inversión concreta sea rentable.','https://datos.madrid.es; https://www.ine.es/dyngs/Prensa/ADRH2023.htm; investigacion_madrid/FASE2_RESULTADOS.md a FASE5_RESULTADOS.md.');
txt(s,'Fuentes complementarias',80,185,1100,55,34,red,true);txt(s,'Censo y padrón de 2026 · renta de 2023\nPrecios y condiciones de menús publicados',80,250,1100,120,31);txt(s,'Uso en la memoria',80,415,1100,55,34,red,true);txt(s,'Contextualizar competencia y límites de decisión\nLa rentabilidad requiere demanda y costes observados',80,477,1100,120,31);
s=slide('Conclusiones y siguientes mejoras','La conclusión principal es que puedo estimar valoraciones históricas con una mejora moderada sobre una referencia sencilla, explicar parte del comportamiento del modelo y demostrar una aplicación reproducible. La lección es elegir variables según su disponibilidad y no confundir rating con éxito económico. La siguiente mejora sería validar con una captura independiente y actual, y medir la utilidad real de la herramienta. Gracias.','Memoria revisada, secciones 6 a 10.',true);
txt(s,'La mejora predictiva depende de la información disponible',80,200,1100,105,35,'#FFFFFF',true);txt(s,'Datos adecuados, interpretación y una aplicación reproducible',80,360,1100,100,32,'#F4E9D8');txt(s,'Pendiente: validación externa y temporal; impacto en uso real',80,530,1100,85,29,'#FFFFFF');
await fs.writeFile(B+'/resultados/guion_slides.json',JSON.stringify(speeches,null,2));
let script='# Guion revisado del vídeo\n\nPeng Chen · 10 diapositivas · objetivo: menos de 5 minutos.\nEnsayar y medir la duración real; no basta con estimarla por palabras.\n\n';for(let i=0;i<speeches.length;i++)script+=`## ${i+1}. ${speeches[i].title.replaceAll('\n',' ')}\n\n${speeches[i].text}\n\n`;
script+='## Grabación\n\nUsar presentacion_revisada_v2.pptx. Voz del alumno obligatoria; cámara opcional. Entregar MP4 de hasta 5 minutos y procurar no superar 50 MB. Esta revisión no incluye un vídeo grabado.\n';await fs.writeFile(B+'/entrega/guion_revisado.md',script);
await(await PresentationFile.exportPptx(p)).save(B+'/build/candidate.pptx');
for(let i=0;i<p.slides.items.length;i++){let b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(B+`/build/revisada-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
let result=await finalizePresentation({workspaceDir:B,candidatePath:B+'/build/candidate.pptx',finalPath:B+'/build/presentacion_base.pptx',pythonExecutable:process.env.RUNTIME_PYTHON,integrityValidatorPath:SK+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:SK+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit','--require-native-table-slide','5'],requiredNativeTableOwnerSlides:[5],requiredNativeChartOwnerSlides:[3,6,7],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[family]},verifyArtifactToolImport:true,receiptPath:B+'/build/presentation-v2.validation.json'});
console.log(JSON.stringify(result));
